apiVersion: v1
kind: List
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: label-studio-backend-grounding-dino
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: label-studio-backend-grounding-dino
      template:
        metadata:
          labels:
            name: label-studio-backend-grounding-dino
        spec:
          containers:
            - name: grounding-dino-backend
              image: docker.io/heartexlabs/label-studio-ml-backend:grnddino-master
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: '2'
                  memory: 6Gi
                  nvidia.com/gpu: '1'
                requests:
                  cpu: '1'
                  memory: 2Gi
                  nvidia.com/gpu: '1'              
              env:
                - name: BASIC_AUTH_USER
                  value: ""
                - name: BASIC_AUTH_PASS
                  value: ""
                - name: MODEL_DIR
                  value: /data/models
                - name: WORKERS
                  value: "2"
                - name: THREADS
                  value: "4"
                - name: LOG_LEVEL
                  value: DEBUG
                - name: BOX_THRESHOLD
                  value: "0.30"
                - name: TEXT_THRESHOLD
                  value: "0.25"
                - name: NVIDIA_VISIBLE_DEVICES
                  value: all  
                - name: LABEL_STUDIO_URL
                  valueFrom:
                    secretKeyRef:
                      name: lbl-studio-ui-items 
                      key: LBL_STUDIO_UI_URL
                - name: LABEL_STUDIO_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: lbl-studio-ui-items 
                      key: LBL_STUDIO_ACCESS_TOKEN   
              ports:
                - containerPort: 9090
                  protocol: TCP
          tolerations:
            - key: odh-notebook
              operator: Exists
              effect: NoSchedule
  - kind: Service
    apiVersion: v1
    metadata:
      name: label-studio-backend-grounding-dino
      labels:
        name: label-studio-backend-grounding-dino
    spec:
      ports:
        - port: 9090
          protocol: TCP
          targetPort: 9090
      selector:
        name: label-studio-backend-grounding-dino
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: label-studio-backend-grounding-dino
      labels:
        name: label-studio-backend-grounding-dino
    spec:
      port:
        targetPort: 9090
      to:
        kind: Service
        name: label-studio-backend-grounding-dino