apiVersion: v1
kind: List
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: custom-flair-label-studio-ml
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: custom-flair-label-studio-ml
      template:
        metadata:
          labels:
            name: custom-flair-label-studio-ml
        spec:
          containers:
            - name: custom-flair-label-studio-ml
              image: quay.io/rhkp/custom-label-studio-ml-flair-backend:0.0.0
              imagePullPolicy: Always
              env:
                - name: MODEL_DIR
                  value: /data/models
                - name: FLAIR_MODEL_NAME
                  value: ner-multi
                - name: WORKERS
                  value: "1"
                - name: THREADS
                  value: "8"
                - name: LOG_LEVEL
                  value: DEBUG                            
              ports:
                - containerPort: 9090
                  protocol: TCP
  - kind: Service
    apiVersion: v1
    metadata:
      name: custom-flair-label-studio-ml
      labels:
        name: custom-flair-label-studio-ml
    spec:
      ports:
        - port: 9090
          protocol: TCP
          targetPort: 9090
      selector:
        name: custom-flair-label-studio-ml
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: custom-flair-label-studio-ml
      labels:
        name: custom-flair-label-studio-ml
    spec:
      port:
        targetPort: 9090
      to:
        kind: Service
        name: custom-flair-label-studio-ml