apiVersion: v1
kind: List
items:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: label-studio-backend-easyocr
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: label-studio-backend-easyocr
      template:
        metadata:
          labels:
            name: label-studio-backend-easyocr
        spec:
          containers:
            - name: easyocr-backend
              image: docker.io/heartexlabs/label-studio-ml-backend:easyocr-master
              imagePullPolicy: Always
              env:
                - name: BASIC_AUTH_USER
                  value: ""
                - name: BASIC_AUTH_PASS
                  value: ""
                - name: MODEL_DIR
                  value: /data/models
                - name: WORKERS
                  value: "1"
                - name: THREADS
                  value: "8"
                - name: LOG_LEVEL
                  value: DEBUG
                - name: LABEL_STUDIO_URL
                  valueFrom:
                    secretKeyRef:
                      name: lbl-studio-ui-items 
                      key: LBL_STUDIO_UI_URL
                - name: LABEL_STUDIO_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: lbl-studio-ui-items 
                      key: LBL_STUDIO_ACCESS_TOKEN             
              ports:
                - containerPort: 9090
                  protocol: TCP
  - kind: Service
    apiVersion: v1
    metadata:
      name: label-studio-backend-easyocr
      labels:
        name: label-studio-backend-easyocr
    spec:
      ports:
        - port: 9090
          protocol: TCP
          targetPort: 9090
      selector:
        name: label-studio-backend-easyocr
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: label-studio-backend-easyocr
      labels:
        name: label-studio-backend-easyocr
    spec:
      port:
        targetPort: 9090
      to:
        kind: Service
        name: label-studio-backend-easyocr